### ISSUE TITLE
Font-size missing required family

### ISSUE THREAD

**Issue by peterdillon** [jedmao/postcss-font-pack#1]
Fatal error: [postcss-font-pack] font-size missing required family

I have no idea what that problem is:
font-packs.json has:

``` json
{
     "roboto": {
        "family": ["Roboto", "Arial", "sans-serif"],
        "propGroups": [
            {}
        ]
    }
}
```

Grintfile has:

``` js
require('postcss-font-pack')({packs: require('./font-packs.json')}),
```

Main css has:

``` css
.foo {
    font: 1rem/1.2 roboto;
}
```

**Comment by jedmao** [comment]
I think you can remove the `propGroups` if you're not defining any. Give that a try?

**Comment by jedmao** [comment]
Still, it shouldn't be failing. I need to write a test case for this and fail gracefully.

**Comment by jedmao** [comment]
@peterdillon did you ever figure out what was going on here?

**Comment by jedmao** [comment]
@peterdillon I wrote a test that matches your scenario exactly and was unable to reproduce the issue. Let me know if this is somehow still an issue, but I'm closing it now in lieu of the working test.
